//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDAClehteng.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShipView
    {
        public int Ship_Id { get; set; }
        public string Ship_Place { get; set; }
        public System.DateTime Ship_Depart { get; set; }
        public System.DateTime Ship_Arrived { get; set; }
        public string Status { get; set; }
    }
}
